# fly.toml app configuration file for stocker-2xbjqq

app = 'stocker-2xbjqq'
primary_region = 'ams'

[build]

[env]
  PERSISTENT_DATA_DIR = "/data"
  SMTP_HOST           = "mail.privateemail.com"
  SMTP_PORT           = "587"
  SMTP_USER           = "info@gultechs.net"
  SITE_BASE_URL       = "https://stocker.gultechs.net"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    grace_period = "15s"
    interval = "30s"
    method = "GET"
    path = "/health"
    timeout = "5s"

[[mounts]]
  source = "stocker_data"
  destination = "/data"
  processes = ["app"]

[[vm]]
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 2048
