services:
  - type: web
    name: stocker
    env: python
    buildCommand: pip install -r Stocker/requirements.txt
    startCommand: cd Stocker && gunicorn app:app --bind 0.0.0.0:$PORT
    plan: free
    autoDeploy: true
