[supervisord]
nodaemon=true

[program:emulator]
command=python3 /app/emulator/emulator.py
autostart=true
autorestart=true

[program:automation_script]
command=python3 /app/app/script.py
autostart=true
autorestart=true
